
package channelsoft.server.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherImpl", targetNamespace = "http://impl.server.channelsoft.com/")
@XmlSeeAlso({
        channelsoft.server.impl.ObjectFactory.class
})
public interface WeatherImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWeatherByCity", targetNamespace = "http://impl.server.channelsoft.com/", className = "com.channelsoft.server.impl.GetWeatherByCity")
    @ResponseWrapper(localName = "getWeatherByCityResponse", targetNamespace = "http://impl.server.channelsoft.com/", className = "com.channelsoft.server.impl.GetWeatherByCityResponse")
    @Action(input = "http://impl.server.channelsoft.com/WeatherImpl/getWeatherByCityRequest", output = "http://impl.server.channelsoft.com/WeatherImpl/getWeatherByCityResponse")
    public String getWeatherByCity(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
